AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deployment pipeline for cfn-stack-notifications'

Parameters:
  Repo:
    Type: String
    Default: jeshan/cfn-stack-notifications
  PrivateBucket:
    Type: String

Resources:
  Project:
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      Cache:
        Type: NO_CACHE
      Description: deploys cfn-stack-notifications to all of my accounts
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.6.5
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: PRIVATE_BUCKET
            Value: !Ref PrivateBucket
          - Name: REPO
            Value: !Ref Repo
      Name: deploy-cfn-stack-notifications
      ServiceRole: !GetAtt 'CodeBuildServiceRole.Arn'
      Source:
        GitCloneDepth: 1
        InsecureSsl: false
        Location: !Sub https://github.com/${Repo}
        ReportBuildStatus: false
        Type: GITHUB
        BuildSpec: |
          version: 0.2

          phases:
            pre_build:
              commands:
                - pip3 install sceptre #sceptre-aws-resolver
            build:
              commands:
                - aws s3 sync s3://${PRIVATE_BUCKET}/github.com/${REPO}/master .
                - python configure-aws-cli.py ${REPO}
                - python run-sceptre-all.py
                - ./upload-public-templates.sh
      TimeoutInMinutes: 15
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
    Type: AWS::CodeBuild::Project

  CodeBuildServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - !Ref LogManagedPolicy
        - !Ref DeployManagedPolicy
        - !Ref TemplateManagedPolicy
      Path: /service-role/
      RoleName: cfn-stack-notifications-deployer
    Type: AWS::IAM::Role

  LogManagedPolicy:
    Properties:
      Description: Policy used in trust relationship with CodeBuild
      Path: /service-role/
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

  DeployManagedPolicy:
    Properties:
      Description: Policy used in trust relationship with CodeBuild
      Path: /service-role/
      PolicyDocument:
        Statement:
          - Action:
              - cloudformation:DescribeStackEvents
              - cloudformation:CreateStack
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStackResources
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:GetStackPolicy
            Effect: Allow
            Resource: arn:aws:cloudformation:*:*:stack/cfn-stack-notifications-*/*
          - Action:
              - cloudformation:DescribeStacks
            Effect: Allow
            Resource: '*'
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Resource: '*'
          - Action:
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:ListChangeSets
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

  TemplateManagedPolicy:
    Properties:
      Description: Policy used in trust relationship with CodeBuild
      Path: /service-role/
      PolicyDocument:
        Statement:
          - Action:
              - sns:CreateTopic
              - sns:DeleteTopic
              - sns:GetTopicAttributes
              - sns:SetTopicAttributes
              - sns:ListTopics
            Effect: Allow
            Resource: '*'
          - Action:
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:UpdateFunctionCode
              - lambda:GetFunctionConfiguration
              - lambda:UpdateFunctionConfiguration
              - lambda:AddPermission
              - lambda:RemovePermission
            Effect: Allow
            Resource: '*'
          - Action:
              - iam:GetRole
              - iam:CreateRole
              - iam:DeleteRole
              - iam:UpdateRole
              - iam:PutRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:ListAttachedRolePolicies
              - iam:ListRolePolicies
              - iam:ListPolicyVersions
              - iam:UpdateAssumeRolePolicy
            Effect: Allow
            Resource: '*'
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cfn-stack-notifications-*'
          - Action:
              - events:PutRule
              - events:DeleteRule
              - events:EnableRule
              - events:DisableRule
              - events:DescribeRule
              - events:PutTargets
              - events:RemoveTargets
            Effect: Allow
            Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/cfn-stack-notifications-*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

Outputs:
  CodeBuildServiceRole:
    Value: !Sub '${CodeBuildServiceRole.Arn}'
