AWSTemplateFormatVersion: "2010-09-09"
Description: 'deploy this in target account so that your codebuild project has permissions to deploy to it'

Parameters:
  DeployerRole:
    Type: String
  DlqName:
    Type: String
  EventsTopicName:
    Type: String

Resources:
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref FnPolicy

  FnPolicy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:GetRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/*
          - Effect: Allow
            Action:
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
            Resource: '*'
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Sub arn:aws:sns:*:${AWS::AccountId}:${EventsTopicName}
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${DlqName}
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

  CodebuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-stack-notifications-target
      ManagedPolicyArns:
        - !Ref DeployManagedPolicy
        - !Ref TemplateManagedPolicy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref DeployerRole
            Action: sts:AssumeRole

  DeployManagedPolicy:
    Properties:
      Description: Policy used in trust relationship with CodeBuild
      Path: /service-role/
      PolicyDocument:
        Statement:
          - Action:
              - cloudformation:DescribeStackEvents
              - cloudformation:CreateStack
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStackResources
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:GetStackPolicy
            Effect: Allow
            Resource: !Sub arn:aws:cloudformation:*:${AWS::AccountId}:stack/cfn-stack-notifications-*/*
          - Action:
              - cloudformation:DescribeStacks
            Effect: Allow
            Resource: '*'
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Resource: '*'
          - Action:
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:ListChangeSets
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

  TemplateManagedPolicy:
    Properties:
      Description: Policy used in trust relationship with CodeBuild
      Path: /service-role/
      PolicyDocument:
        Statement:
          - Action:
              - sns:CreateTopic
              - sns:DeleteTopic
              - sns:GetTopicAttributes
              - sns:SetTopicAttributes
              - sns:ListTopics
            Effect: Allow
            Resource: '*'
          - Action:
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:UpdateFunctionCode
              - lambda:GetFunctionConfiguration
              - lambda:UpdateFunctionConfiguration
              - lambda:AddPermission
              - lambda:RemovePermission
            Effect: Allow
            Resource: '*'
          - Action:
              - iam:GetRole
              - iam:CreateRole
              - iam:DeleteRole
              - iam:UpdateRole
              - iam:PutRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:ListAttachedRolePolicies
              - iam:ListRolePolicies
              - iam:GetPolicy
            Effect: Allow
            Resource: '*'
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cfn-stack-notifications-*'
          - Action:
              - events:PutRule
              - events:DeleteRule
              - events:EnableRule
              - events:DisableRule
              - events:DescribeRule
              - events:PutTargets
              - events:RemoveTargets
            Effect: Allow
            Resource: !Sub 'arn:aws:events:*:${AWS::AccountId}:rule/cfn-stack-notifications-*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy

Outputs:
  TargetRole:
    Value: !Sub '${CodebuildRole.Arn}'
  FnRole:
    Value: !Sub '${FnRole.Arn}'
