AWSTemplateFormatVersion: '2010-09-09'
Description: 'adds an sns topic to all your cfn stacks in this region'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TopicName:
    Type: String
    Default: cloudformation-stack-events

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

  Fn:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        import os
        import boto3

        def handler(event, context):
          print('event', event)
          request_parameters = event['detail']['requestParameters']
          response_elements = event['detail']['responseElements']
          if response_elements:
            stack_name = response_elements['stackId']
          elif request_parameters:
            stack_name = request_parameters['stackName']
          else:
            print('Could not find stack name in this event, skipping.')
            return
          client = boto3.client('cloudformation')
          stack_info = client.describe_stacks(StackName=stack_name)['Stacks'][0]
          topics = stack_info['NotificationARNs']
          topic = os.environ['TOPIC']
          if topic not in topics:
            print('adding', topic, 'to', stack_name)
            parameter_input = list(map(lambda x: {'UsePreviousValue': True, 'ParameterKey': x['ParameterKey']}, stack_info['Parameters']))
            client.update_stack(StackName=stack_name, UsePreviousTemplate=True, Parameters=parameter_input, NotificationARNs=topics + [topic], Capabilities=['CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', 'CAPABILITY_AUTO_EXPAND'])
            print('Successfully updated stack')
          else:
            print(topic, 'was already in', stack_name)
      Handler: index.handler
      Timeout: 30
      MemorySize: 128
      Runtime: python3.7
      Policies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
            Resource: '*'
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Ref Topic
      Environment:
        Variables:
          CURRENT_STACK: !Ref AWS::StackId
          TOPIC: !Ref Topic
      Events:
        Cw:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source: ['aws.cloudformation']
              detail-type: ['AWS API Call via CloudTrail']
              detail:
                eventSource: ['cloudformation.amazonaws.com']
                eventName: ['CreateStack', 'UpdateStack']

Outputs:
  TopicArn:
    Value: !Ref Topic
  TopicName:
    Value: !GetAtt Topic.TopicName
